if(CMAKE_TOOLCHAIN_PREFIX)
	set(EXTERNAL_CMAKE_ARGS "${EXTERNAL_CMAKE_ARGS} -DCMAKE_TOOLCHAIN_PREFIX=${CMAKE_TOOLCHAIN_PREFIX}")

	if (NOT CC)
		# Find CC compiler.
		find_program(COMPILER ${CMAKE_TOOLCHAIN_PREFIX}gcc)

		if(NOT COMPILER)
			message(FATAL_ERROR "CC compiler ${CMAKE_TOOLCHAIN_PREFIX}gcc not found!")
		endif()

		set(CMAKE_C_COMPILER ${CMAKE_TOOLCHAIN_PREFIX}gcc)
	else()
		set(CMAKE_C_COMPILER ${CC})
	endif()

	if (NOT CXX)
		# Find CXX compiler.
		find_program(COMPILER ${CMAKE_TOOLCHAIN_PREFIX}g++)

		if(NOT COMPILER)
			message(FATAL_ERROR "CXX compiler ${CMAKE_TOOLCHAIN_PREFIX}g++ not found!")
		endif()

		set(CMAKE_CXX_COMPILER ${CMAKE_TOOLCHAIN_PREFIX}g++)
	else()
		set(CMAKE_CXX_COMPILER ${CXX})
	endif()
endif()

if(CMAKE_SYSROOT)
	set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
	set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
	set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
	set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

	set(EXTERNAL_CMAKE_ARGS ${EXTERNAL_CMAKE_ARGS}
		-DCMAKE_SYSROOT=${CMAKE_SYSROOT}
		-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=${CMAKE_FIND_ROOT_PATH_MODE_PROGRAM}
		-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY}
		-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=${CMAKE_FIND_ROOT_PATH_MODE_INCLUDE}
		-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=${CMAKE_FIND_ROOT_PATH_MODE_PACKAGE}
	)
endif()

if(CMAKE_C_COMPILER)
	set(EXTERNAL_CMAKE_ARGS ${EXTERNAL_CMAKE_ARGS} -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER})
endif()

if(CMAKE_C_FLAGS)
	set(EXTERNAL_CMAKE_ARGS ${EXTERNAL_CMAKE_ARGS} -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS})
endif()

if(CMAKE_CXX_COMPILER)
	set(EXTERNAL_CMAKE_ARGS ${EXTERNAL_CMAKE_ARGS} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER})
endif()

if(CMAKE_CXX_FLAGS)
	set(EXTERNAL_CMAKE_ARGS ${EXTERNAL_CMAKE_ARGS} -DCMAKE_CMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS})
endif()
